import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Nextjs Tutor", //! sayfada metadata tanımlanmazsa default olarak bu yazar.
    template: "%s | Merhaba...", //! sayfada metadata varsa eğer Sayfanın ki %s kısma gelir: Blog | Merhaba... şeklinde.
    absolute: "",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="h-[10dvh] bg-slate-300 text-red-600 p-3 flex justify-center">
          This is head nav side
        </header>
        <main className="h-[85dvh] p-3 bg-teal-200 text-black flex justify-center items-center">
          {children}
        </main>
        <footer className="h-[5dvh] bg-yellow-300 p-3 flex justify-center text-red-500">
          This is footer
        </footer>
      </body>
    </html>
  );
}
